default: &default
  token: <%= ENV["DISCORD_TOKEN"] %>
  steam_api_key: <%= ENV["STEAM_TOKEN"] %>
  loops:
    # ESM::Request::Overseer
    request_overseer:
      check_every: 15

    # ESM::Websocket::Request::Overseer
    websocket_request_overseer:
      check_every: 15

    # ESM::Bot::ResendQueue
    bot_resend_queue:
      check_every: 5
      max_attempts: 5

development:
  <<: *default
  prefix: "~"

test:
  <<: *default
  prefix: "~"

production:
  <<: *default
  prefix: "!"
