default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  host: 'localhost'
  username: esm
  password: password12345

development:
  <<: *default
  database: esm_development

test: &test
  <<: *default
  database: esm_test

production:
  <<: *default
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
  database: <%= ENV["POSTGRES_DATABASE"] %>
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  sslrootcert: <%= ENV["POSTGRES_SSL_CERT"] %>
